# Alacritty .config main toml file
# Customization reference: https://alacritty.org/config-alacritty.html#s10
#################################################################


# Basics, prepare the setup
general.import = [" ",
]		# Any import must be done here
general.working_directory = "None"
general.live_config_reload = true 
general.ipc_socket = true 


# Custom setup, remeber, it is written using toml
# Set up environment variables
[env]
#WINIT_X11_SCALE_FACTOR = "1.0"


# Window connfig
[window]
# --- Terminal pos ---
#dimensions = { columns = 2, lines = 2 }
#position = "None" | { x = <integer>, y = <integer> } No effect hyprland 
# --- Padding ---
padding = { x = 0, y = 0}
dynamic_padding = true 
decorations = "Full"
# --- "Transparency" ---
opacity = 0.69
blur = false		# requires external package (or using some "magic")
# --- Window config (literally) ---
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }  # Only linux and BSD
resize_increments = false


# Scrolling config 
[scrolling]
history = 10000		# Max. lines history
multiplier = 1		# n. lines we scrole at the time


# Fonts set up
[font]
# --- Type ---
normal = { family = "JetBrainsMono Nerd Font", style = "Normal"}
bold = { style = "Bold"}
italic = {style = "Italic"}
bold_italic = {style = "BoldItalic"}
# --- Size and "Position" ---
size = 12.0		# 1080p main display
offset = { x = 0, y = 0 }
glyph_offset = { x = 2, y = 0 }
builtin_box_drawing = true


# Config terminal colors-colorscheme
[colors]
# -------- Cursor --------
cursor = { text = "CellBackground", cursor = "CellForeground" }
# -------- vi mode --------
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
line_indicator = { foreground = "None", background = "None" }
# -------- Misc --------
footer_bar = { foreground = "#ff0000", background = "#d8d8d8"} 
selection = { text = "#181818", background = "#ff0000" }
transparent_background_colors = false
draw_bold_text_with_bright_colors = true
# -------- "Terminal" base color-scheme --------
[colors.primary]
background = '#0a0012'  # Background color
foreground = '#a9b1d6' 	# "Fonts" color
dim_foreground = "#828482"
bright_foreground = "None"
# -------- Search config --------
[colors.search]
matches = { foreground = "#ff0000", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#ac4242" }
# -------- Hints color config --------
[colors.hints]
start = { foreground = "CellForeground", background = "CellBackground" }
end = { foreground = "CellForeground", background = "CellBackground" }
# -------- Base colors setup -------- 
[colors.normal]
black = '#000000'
red = '#FF0000'
green = '#00FF00'
yellow = '#FFFF00'
blue = '#000080'
magenta = '#FF00FF'
cyan = '#00FFFF'
white = '#FFFFFF'


# We define the terminal configs, in my case, zsh
[terminal]
[terminal.shell]
program = '/usr/bin/zsh'
args = ["-l"]


# ******** Might not be accurate **********
# THIS SECTION MIGHT BE CURSED
[colors.bright]
black = '#C0C0C0'
red = '#FF0000'
green = '#00FF00'
yellow = '#FFFF00'
blue = '#1E90FF'
magenta = '#FF00FF'
cyan = '#00FFFF'
white = '#FFFFFF'
